### ISSUE TITLE
How it can prevent from leaving app with goBack?

### ISSUE THREAD

**Issue by peterbartos** [hinok/react-router-last-location#6]
The description states: Easily prevent leaving your app by users.

As history.goBack also updates the lastLocation, I don't know if to show the history back button in UI.

Can I really use this library to prevent leaving my app by history.goBack?

**Comment by hinok** [comment]
Hey @peterbartos ,
By `Easily prevent leaving your app by users.` I've wanted to express that you can use this package to check if `lastLocation === null` to know if someone has already switched routes during the current session.

[Because of security / private matters](https://developer.mozilla.org/en-US/docs/Web/API/Window/history#Notes), there is no way to get list of history entries.

I know that it's far from ideal solution but in our case checking if there is something like `lastLocation` was good enough when we decided to use `history.goBack() or history.go(-1)`.

I've posted some time ago longer explanation and demo here: https://stackoverflow.com/a/46777477/1772171

**Comment by peterbartos** [comment]
I see. After using the `history.goBack()` the library is not able to say if there is history for current app or not. I was thinking that the library logic would need to distinguish between PUSH and POP location changes and based on that create it's own stack to track the "real back location". Not sure if that would be possible.

**Comment by hinok** [comment]
In my opinion It's out of the scope of `react-router-last-location` package but it's good idea to create another small package just for this feature to track all location changes and maintaining a stack of all entries, synchronising it after push / pop / replace.

Still it will not solve the problem what should application do if user reloads the page, where to store history entries: just in memory, local/session storage etc.
